-- MySQL Script generated by MySQL Workbench
-- Mon Apr 20 23:54:45 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
--
-- Modificado para Tarea 2 (Lucas Brule): se extiende `miembro` con apellido,
-- password, tipo y campos condicionales por tipo (carrera/anio_ingreso/depto/
-- cargo/area_investigacion/grado_academico). Se cambia `actividad`: `dia` →
-- `fecha`, `duracion` → `hora_fin`, se agrega `link`, y los valores de ENUM
-- `tipo` ahora coinciden con los del form de Tarea 1.

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tarea2
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tarea2` ;

-- -----------------------------------------------------
-- Schema tarea2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tarea2` DEFAULT CHARACTER SET utf8 ;
USE `tarea2` ;

-- -----------------------------------------------------
-- Table `tarea2`.`region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tarea2`.`region` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tarea2`.`comuna`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tarea2`.`comuna` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NOT NULL,
  `region_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comuna_region1_idx` (`region_id` ASC),
  CONSTRAINT `fk_comuna_region1`
    FOREIGN KEY (`region_id`)
    REFERENCES `tarea2`.`region` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tarea2`.`miembro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tarea2`.`miembro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `apellido` VARCHAR(255) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `tipo` ENUM('Pregrado', 'Postgrado', 'Funcionario', 'Academico') NOT NULL,
  `fecha_registro` DATETIME NOT NULL,
  `comuna_id` INT NOT NULL,
  `carrera` VARCHAR(255) NULL,
  `anio_ingreso` INT NULL,
  `departamento` VARCHAR(255) NULL,
  `cargo` VARCHAR(255) NULL,
  `area_investigacion` VARCHAR(255) NULL,
  `grado_academico` ENUM('Licenciado', 'Magister', 'Doctor') NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_miembro_comuna1_idx` (`comuna_id` ASC),
  CONSTRAINT `fk_miembro_comuna1`
    FOREIGN KEY (`comuna_id`)
    REFERENCES `tarea2`.`comuna` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tarea2`.`actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tarea2`.`actividad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `miembro_id` INT NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `descripcion` TEXT NULL,
  `fecha` DATE NOT NULL,
  `hora_inicio` VARCHAR(5) NOT NULL,
  `hora_fin` VARCHAR(5) NOT NULL,
  `tipo` ENUM('Artistica', 'Deportiva', 'Tecnologica', 'Social', 'General') NOT NULL,
  `link` VARCHAR(500) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_actividad_miembro1_idx` (`miembro_id` ASC),
  CONSTRAINT `fk_actividad_miembro1`
    FOREIGN KEY (`miembro_id`)
    REFERENCES `tarea2`.`miembro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tarea2`.`foto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tarea2`.`foto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ruta_archivo` VARCHAR(300) NOT NULL,
  `nombre_archivo` VARCHAR(300) NOT NULL,
  `actividad_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_foto_actividad1_idx` (`actividad_id` ASC),
  CONSTRAINT `fk_foto_actividad1`
    FOREIGN KEY (`actividad_id`)
    REFERENCES `tarea2`.`actividad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
